apiVersion: batch/v1
kind: Job
metadata:
  name: llava-training-cuda128-openai-zero3-bs16
spec:
  template:
    spec:
      priorityClassName: normal # important
      containers:
        - name: llava-train
          image: registry.datexis.com/jwesterhoff/llava-train-cuda128-openai:latest
          imagePullPolicy: Always # to force pulling the newest image
          workingDir: /src
          command: ["/bin/bash", "./scripts/v1_5/finetune.sh"]
          env:
          - name: PYTHONPATH
            value: "/src"
          - name: LANG
            value: 'C.UTF-8'
          - name: PYTHONUNBUFFERED
            value: '1'
          # - name: CUDA_LAUNCH_BLOCKING
            # value: '1'  # Add this for more detailed error messages
          - name: WANDB_API_KEY
            valueFrom:
              secretKeyRef:
                name: wandb-api
                key: WANDB_API_KEY
          volumeMounts:
            - name: llava-datasets-pvc
              mountPath: /llava-datasets
            - name: llava-checkpoints-pvc
              mountPath: /llava-checkpoints
            - name: dshm
              mountPath: /dev/shm
          resources:
            limits:
              nvidia.com/gpu: "8"
              cpu: "16"
              memory: "256Gi"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: gpu
                    operator: In
                    values:
                      - b200
      volumes:
        - name: llava-datasets-pvc
          persistentVolumeClaim:
            claimName: llava-datasets-pvc
        - name: llava-checkpoints-pvc
          persistentVolumeClaim:
            claimName: llava-checkpoints-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
  backoffLimit: 0
